plugins {
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

version = '1.0.0'
group = 'com.depixar.sizemod'
archivesBaseName = 'sizemod'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            mods { sizemod { source sourceSets.main } }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            mods { sizemod { source sourceSets.main } }
        }
    }
}

repositories {
    mavenCentral()
    maven { url "https://api.modrinth.com/maven" }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'

    // Теперь сборщик будет видеть классы Pehkui при компиляции
    compileOnly fg.deobf("maven.modrinth:pehkui:3.7.8+1.14.4-1.21")
}

jar {
    manifest {
        attributes([
            'Specification-Title'     : 'sizemod',
            'Specification-Vendor'    : 'depixar',
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion,
            'Implementation-Vendor'   : 'depixar',
        ])
    }
}

processResources {
    var replaceProperties = [minecraft_version: '1.20.1', forge_version: '47.2.0', mod_version: version]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties
    }
}
